version: "3"
services:
  notes-app:
    build: .
    container_name: notes-app
    ports: ["3010:3000"]      
    volumes: [".:/usr/src/app"]      
    command: ./entrypoint.sh
    working_dir: /usr/src/app

