version: "3"
services:
  notes-db:
    image: mariadb:10-focal
    container_name: notes-db
    volumes: ["db:/var/lib/mysql"]
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=TRUE

  notes-app:
    build: .
    container_name: notes-app
    ports: ["3010:3000"]      
    volumes: [".:/usr/src/app"]      
    command: ./entrypoint.sh
    working_dir: /usr/src/app
    depends_on: ["notes-db"]

volumes: 
  db:
